### ISSUE TITLE
Warning raised while executing mc.superpose()

### ISSUE THREAD

**Issue by ManonMarchand** [krlennon/mastercurves#2]
Hi! 

Thanks a lot for this piece of code and your presentation of it at the last AERC. 

It works beautifully with my own data but I have a list of warnings raised when calling the `superpose` function.
They all look like these: 

`C:\Python39\lib\site-packages\sklearn\gaussian_process\kernels.py:430: ConvergenceWarning: The optimal value found for dimension 0 of parameter k1__k1__k1__k1__alpha is close to the specified upper bound 100000.0. Increasing the bound and calling fit again may find a better value.`

`C:\Python39\lib\site-packages\sklearn\gaussian_process\kernels.py:420: ConvergenceWarning: The optimal value found for dimension 0 of parameter k1__k1__k2__constant_value is close to the specified lower bound 1e-05. Decreasing the bound and calling fit again may find a better value.`

Do you think it would be worth changing these bounds? I couldn't find where they are in `mc.py`

**Comment by krlennon** [comment]
Thanks, and glad the package is working well for you! There are a few warnings that might be raised when using the package, which typically come from `scikit-learn` (it's a pretty warning-heavy package). I've seen this one pop up in certain circumstances, but I wanted to leave the default bounds from `scikit-learn`, because these bounds are already quite loose and it's hard to say how they should be changed in general while keeping the package agnostic to specific features of data.

The internal kernel function used in a `MasterCurve` is exposed to the user, and you can manually adjust it to avoid warnings like this one. You'll just have to pass custom bounds to a user-defined kernel (e.g. `RationalQuadratic(alpha_bounds=(1E-5,1E6))`), and then use the `mastercurves.MasterCurve.set_gp_kernel` method to set this as the kernel for the `MasterCurve` object before calling `superpose`. Default bounds can be found in the [docs](https://scikit-learn.org/stable/modules/gaussian_process.html) for `scikit-learn`.

I've added a [tutorial](https://krlennon-mastercurves.readthedocs.io/en/latest/kernels.html) to the docs, which provides step-by-step instructions for adjusting the kernel and hyperparameters. Thanks again for this feedback!
